services:
  inventory_app:
    container_name: autowpp_app
    image: postgres
    environment:
      POSTGRES_DB: autowpp_database
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    volumes:
      - autowpp_app:/data/autowpp_app
    ports:
      - "5434:5432"
    networks:
      - autowpp_app_net
    restart: unless-stopped

networks:
  autowpp_app_net:
    driver: bridge

volumes:
  autowpp_app:
